== Coordinate Reference System (CRS)

=== Horizontal reference system

Spatial data are expressed in latitude and longitude geographic
coordinates in reference to a horizontal reference system.

The longitude is stored as a negative number to represent a position west
of the prime meridian (stem:[0 "unitsml(deg)"]). Latitude is stored as a
negative number to represent a position south of the equator.

Latitude and Longitude may also be stored as textual strings. This is
required so that positions may be described in the exact format that they
are described in the source document they were extracted from. If a
position is described in a source document in degrees, minutes and seconds
then this description must be retained in the textual string as degrees,
minutes and seconds because a conversion to decimal degrees would
constitute a change in format from its defined value. The same latitude
and longitude position may also be stored as a set of real numbers within
a GIS system so that it can be used digitally. That is, the values used in
a source document must be preserved, but points and other geometric
primitives may have multiple representations.

Different reference systems are used by various nations. Since data may
come from different sources, multiple coordinate reference systems may be
used in the same dataset.

=== Projection

S-130 data products are unprojected.

=== Temporal reference system

Time is measured by reference to Calendar dates and Clock time in
accordance with <<ISO19108,clause="5.4.4">>.

=== Polygonal Demarcations of Global Sea Areas data and scale

S-130 data must be compiled in the best applicable scale. The use of the
data itself is "scale independent". That means that the data can be used
at any scale. <<S100>> allows the association of multiple spatial
attributes to a single feature instance. In principle, each of these
spatial attributes can be qualified by maximum and minimum scales.

For example, it is possible, within one dataset, to have a single instance
of a feature that has more than one area geometry. Each of these
geometries has different max/min scale attributes. Moreover, due to
cluttering in smaller scales, the minimum scale attribute may be used to
turn off portrayal of some features at smaller scales.
