== Data Capture and Classification

The production process used to generate S-130 products may be described
in the dataset metadata. Since <<S100>> discovery metadata does not
provide distinct classes or fields for describing the production process,
the descriptions may be combined into a text string in the _comment_
field of S100_DatasetDiscoveryMetadata (<<cls-12.2.4>>).

[[tab-8-1]]
.Data capture information
[cols="a,a,a,a",options=header]
|===
| Item Name | Description | Multiplicity | Type

| dataSource | Identification of the kinds of data sources usable to product datasets compliant with S-130 | 0..* | CharacterString
| productionProcess | Link to a textual description of the production process (including encoding guide) applicable to the datasets compliant with S-130 | 0..* | CharacterString (URL)
|===

=== Data Encoding and Product Delivery

==== Data Encoding

The principal encoding will be the S-100 profile of the Open Geospatial
Consortium (OGC), Geography Markup Language (GML) format. GML is an XML
grammar designed to express geographical features. It serves as a
modelling language for geographic systems as well as an open interchange
format for geographic transactions. The GML encoding is in conformance
with <<S100,part=10b>>.

==== Types of Datasets

A dataset is a grouping of features, attributes, geometry and metadata
which comprises a specific coverage. The following types of S-130 dataset
may be produced and contained within an exchange set:

[[tab-8-2]]
.S-130 dataset types
[cols="a,a",options=header]
|===
| Dataset | Explanations

| New dataset (base dataset): | Data for an area different (in coverage and/or extent) to existing datasets.
| New Edition of a dataset: | A re-issue plus new information which has not been previously distributed by Updates. Each New Edition of a dataset must have the same name as the dataset that it replaces and should have the same spatial extents. The edition number in the dataset discovery metadata must increment up by one from the previous edition.
| Update | Changing some information in an existing dataset
| Reissue | A complete dataset including all the updates applied to the original dataset up to the date of the re-issue.
| Cancellation | Used to cancel dataset.
|===

==== Data Format for Update Datasets

Update datasets use the same data format as base datasets.

S-130 uses the "whole-object update" approach described in
<<S100,clause="10b-11.5">> and elaborated below.

* Updates are only defined at a feature or information type level.
Individual attribute values cannot be updated without updating the
feature or information type instance as a whole.
* Updates can only add new instances or replace existing instances of
feature or information types.
* Updated feature or information type instances must retain the GML
identifier for their predecessor instances in the base dataset.
* Feature or information type instances in an update dataset must include
all attributes and associations for the original instance, since the
whole data object is being replaced.
* It is not possible to update associations except by replacing all
feature or information type instances affected by a change to references.
* If an update to a feature or information type involves no change to its
associations, either to the original feature, or from the original to
another feature or information type, it is not necessary to include the
associated instances in the update dataset (unless they are also being
updated).
* It is not possible to delete feature or information type instances
through an update. A new edition of the dataset must be issued to delete
an instance without replacement.

==== Data Format for Cancellation Datasets

Cancellation datasets use the same data format as base datasets but
include no spatial objects or instances of feature or information types.

=== Numeric Attribute Encoding

Floating point and integer attribute values must not contain leading
zeros. Floating point attribute values must not contain non-significant
trailing zeros.

=== Text Attribute Values

Character strings must be encoded using the character set defined in
<<ISO10646-1>>, in Unicode Transformation Format-8 (UTF-8).

=== Mandatory Attribute Values

All mandatory attributes are identified in the Feature Catalogue and
summarised in Annex A -- Data Classification and Encoding Guide.

=== Unknown Attribute Values

When a mandatory attribute code or tag is present but the attribute value
is missing, it means that the producer wishes to indicate that this
attribute value is unknown. Missing mandatory attributes must be "nilled".

Optional attributes must be omitted altogether if the value is unknown or
missing. They must not be "nilled."

[example]
An instance of *SourceInformation* has unknown sourceType (mandatory
attribute). The instance could be coded as:

[source%unnumbered]
----
<SourceInformation>
  <sourceIndication>
    <source>...</source>
    <sourceType xsi:nil="true"/>
  </sourceIndication>
</SourceInformation>
----

=== Structure of dataset files

==== Sequence of objects

The order of data objects in each dataset file is described below:

* Dataset Identification Information
* Dataset structure information
* Spatial records for by-reference geometries
** Point
** Curve
** Composite Curve
** Surface
* Information objects
* Feature objects (Geometry may be encoded inline or by reference.)
** Meta features
** Geo features

=== Object identifiers

A unique worldwide identifier of feature records is provided through a
feature attribute (featureIdentifier).

The numeric component of featureIdentifier attributes must be encoded as:

`YYYYYYXXXXXX`

where:

* `YYYYYY`: number computed by adding an offset of 90.000 to the latitude
coordinate of the centroid in decimal degrees (3 decimals);
* `XXXXXX`: number computed by adding 180.000 to the longitude coordinate
of the centroid in decimal degrees (3 decimals);
* leading and trailing zeros are used as necessary so that each number
computed as above is exactly 6 digits.

[example]
A feature with a centroid of stem:[50.0 "unitsml(deg)" " N"] stem:[40.0
"unitsml(deg)" " W"] (latitude=+50.0, longitude=-40.0 in decimal degrees)
will have numeric identifier component `140000140000`

Features, information types, collection objects, meta features, and
geometries (inline or external) are all required by the schema to have a
*gml:id* attribute with a value that is unique within the dataset. The
*gml:id* values must be used as the reference for the object from another
object in the same dataset or another dataset.

=== Data coverage

All areas of a dataset must be covered by a *DataCoverage* meta feature.

An update dataset must not change the limit of a *DataCoverage* feature
for the base dataset. Where the limit of a *DataCoverage* feature for a
base dataset is to be changed, this must be done by issuing a new edition
of the dataset.

=== Data overlap

S-130 datasets may overlap other S-130 datasets.
